languageCode = "ru"
languageName = "Русский"
weight = 2
title = "HIlight3R"

[params]
displayName = "Русский"
isoCode = "ru"
rtl = false
dateFormat = "2 января 2006"
copyright = "Copyright © 2024 HIlight3R"

[author]
name = "HIlight3R"
image = "img/avatar.jpg"
headline = "Немножко обо мне..."
bio = "A little bit about me"
links = [
    { github = "https://github.com/HIlight3R" },
    { discord = "https://dsc.bio/HIlight3R" },
    { telegram = "https://t.me/HIlight3R" },
    { reddit = "https://www.reddit.com/user/HIlight3R" },
    { steam = "https://steamcommunity.com/id/HIlight3R" },
    { spotify = "https://open.spotify.com/user/31annn564b5fkncvg6jbafxvlvui" },
    { keybase = "https://keybase.io/HIlight3R" }
]
